# -*- coding: utf-8 -*-
"""fibonacci series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uhlRIz7326CvHOzkJGId5b8ZcOWqSFS
"""

def fibonacci(n):
    fib_series = [0, 1]
    while len(fib_series) < n:
        fib_series.append(fib_series[-1] + fib_series[-2])
    return fib_series

# Example usage
num_terms = int(input("Enter the number of terms: "))
print("Fibonacci Series up to", num_terms, "terms:")
print(fibonacci(num_terms))