# -*- coding: utf-8 -*-
"""print positive num.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uhlRIz7326CvHOzkJGId5b8ZcOWqSFS
"""

def print_positive_numbers(lst):
    positive_numbers = []
    for num in lst:
        if num > 0:
            positive_numbers.append(num)
    print("Positive numbers in the list:", end=" ")
    for i in range(len(positive_numbers)):
        if i != len(positive_numbers) - 1:
            print(positive_numbers[i], end=", ")
        else:
            print(positive_numbers[i])

# Example usage
list1 = [12, -7, 5, 64, -14]
print_positive_numbers(list1)