# -*- coding: utf-8 -*-
"""set operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uhlRIz7326CvHOzkJGId5b8ZcOWqSFS
"""

# Define two sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

# Union of sets E and N
union = E.union(N)
print("Union of E and N is", union)

# Intersection of sets E and N
intersection = E.intersection(N)
print("Intersection of E and N is", intersection)

# Difference of sets E and N
difference = E.difference(N)
print("Difference of E and N is", difference)

# Symmetric difference of sets E and N
symmetric_difference = E.symmetric_difference(N)
print("Symmetric difference of E and N is", symmetric_difference)